object Versions {
    const val hilt = "2.48"
    const val hiltCompiler = "1.0.0-alpha01"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutines = "1.7.3"
    const val navcompose = "2.7.0"
    const val splashScreen = "1.0.0-alpha01"
    const val coil = "2.2.0"
    const val pager = "0.36.0"
    const val swiperefresh = "0.30.1"
}